Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,6 +7,27 @@ on:
 
 jobs:
   build:
+    env:
+      SERVER_URL: 127.0.0.1
+      SERVER_PORT: 8080
+      FULL_BUILD: true
+
+      APP_PORT: 8080
+      APP_ENV: production
+      
+      TRANSLATION_API_URL: http://127.0.0.1:5000
+      TRANSLATION_API_TIMEOUT: 20s
+      
+      GITHUB_API_URL: https://api.github.com
+      GITHUB_API_TIMEOUT: 10s
+      GITHUB_API_USER_LOGIN: caoancap
+      GITHUB_API_ORGS_LOGIN: "[\"cao-ancap\"]"
+
+      REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
+      REDIS_USER: ${{ secrets.REDIS_USER }}
+      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
+      REDIS_DB: ${{ secrets.REDIS_DB }}
+      REDIS_CACHE_TTL: 168h
 
     runs-on: ubuntu-latest
     timeout-minutes: 30
@@ -22,31 +43,78 @@ jobs:
         persist-credentials: false
         repository: caiocampos/caiocampos.github.io
         ref: nx-app
+        
+    - name: Get config
+      run: curl -O https://raw.githubusercontent.com/caoancap/readme-base/refs/heads/main/config.json
+      
+    - name: copy config
+      run: cp ./config.json ./src/config.json
+
+    - name: Checkout cached-translation-middleware
+      uses: actions/checkout@v6
+      with:
+        persist-credentials: false
+        repository: caoancap/cached-translation-middleware
+        path: middleware
+
+    - name: Set up Go
+      uses: actions/setup-go@v6
+      with:
+        go-version: 1.26
+
+    - name: Build server
+      working-directory: ./middleware
+      run: bash server-build.sh
+
+    - name: Give permission to run server
+      run: chmod +x ./middleware/server
+
+    - name: Run server
+      run: |
+        nohup ./middleware/server > out.log 2>&1 &
+
+        PROCESS_PID=$!
+        echo "APP_PID=$PROCESS_PID" >> $GITHUB_ENV
+        
+        sleep 5
+        
+        if pgrep -f "server" > /dev/null
+        then
+            echo "Server running in background"
+        else
+            echo "Server failed"
+            exit 1
+        fi
+
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v6
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - name: Get config
-      run: curl -O https://raw.githubusercontent.com/caoancap/readme-base/refs/heads/main/config.json
-    - name: copy config
-      run: cp ./config.json ./src/config.json
+
     - name: Install
-      run: npm install
+      run: yarn install
+
     - name: Run translate service
       run: |
            npm run libretranslate
            docker ps
+
     - name: Build
-      run: |
-           export SERVER_URL=127.0.0.1
-           export FULL_BUILD=true
-           npm run build
+      run: yarn build
+
     - name: Stop translate service
+      if: always()
       run: npm run libretranslate-stop
+
+    - name: Stop server
+      if: always()
+      run: kill ${{ env.APP_PID }}
+      
     - name: Adjustment
       run: |
            cp .nojekyll ./out/.nojekyll
+           
     - name: Deploy
       uses: JamesIves/github-pages-deploy-action@v4
       with:
